export const TESTTYPE = "TESTTYPE";
export const LOGINTYPE = "LOGINTYPE";
export const LOGINSUCCESSTYPE = "LOGINSUCCESSTYPE";
export const LOGINERRORTYPE = "LOGINERRORTYPE";
export const LOGINBUTTONCLICKTYPE = "LOGINBUTTONCLICKTYPE";